https://philpapers.org

/rec/CHAIAT-11


https://philpapers.org/browse/idealism?start=0&freeOnly=&cId=163&onlineOnly=&sort=pubYear&proOnly=on&langFilter=&showCategories=on&newWindow=on&publishedOnly=&categorizerOn=&limit=50&sqc=&hideAbstracts=&cn=idealism&filterByAreas=&new=1&format=html&jlist=&ap_c1=&ap_c2=

Idealism


https://www.facebook.com/groups/idealistphilosophy/?ref=br_rs

History, summary of current:
	http://critique-of-pure-interest.blogspot.com/2016/01/idealism-past-present-and-future.html

Connections to math, QM
Opposition drove development of analytic philosophy


Tegmark fits in, but lacks a reference to the part of the cosmos with phenomenology

Experience of passage of time
	Block universe
	Anthropomorhism
Multiple worlds

Taxomony of idealism theories
	Hindu
	Christian
What was the position of the famous philosophers?
	Which were realist vs idealist
Acosmic
	Role of empirical world
	
Why was it so popular in western and Hindu philosophy? Greek?
Why was it discredited in the West?


German idealism
	Hegel
	Schoepenhauer
	Made physics be unattractive, so Jews could get jobs there
	Realism
		Einstein -> Bohm
	Copenhagen - don't ask
	
Why was plato idealist?
	See Phaedo: assumes people are owned by a God, our understanding comes from remembering from before birth, the soul is more divine like than the body
	
Forms: conventional reason for rejecting forms was the Third Man argument from Aristotle
	• Claims it leads to an infinite regress of intermediates, but that doesn't recognize how the relationships can be modeled with connection entities
	• Examples of forms that Plato gives are beauty, bigness, tallness which are of course relative based on subject and and context. 
	• The forms can still exist in the mind. Are number thoughts connection to the form for those numbers?

Kant: https://www.britannica.com/topic/transcendental-idealism

Jung
* describes introversion and extroversion as reminiscent of idealism and materialism
** believed in soveriegnty of psyche over physical, but accepted that they are connected

https://en.wikipedia.org/wiki/Universal_mind

Idealism, in the context of philosophy, claims that reality is fundamentally of a mental nature, or is in some other way immaterial. This belief has played an important role throughout history, including Hinduism, Platonism, Christianity, and notably among the German Idealists such as Kant, Hegel, Schopenhauer and others.

Idealism fell out of favor for a variety of reasons, including the success of science based on the physical world to explain what we see. Nevertheless, more recent developments in quantum physics strongly challenge the notion that reality is based entirely on a physical world.

https://en.wikipedia.org/wiki/Idealism
https://en.wikipedia.org/wiki/Physicalism
https://www.technologyreview.com/s/613092/a-quantum-experiment-suggests-theres-no-such-thing-as-objective-reality/


