using System;
using System.Diagnostics;
using reslab.TestUtil;

namespace reslab
{
    class TfcBuiltEx2Regen6: TfcBuilt, Ibo
    {
        public TfcBuiltEx2Regen6(Tfm tfm, PouEx2 pou) : base(tfm, pou) {}
        public override Pou pouBuildOutline(Iss iss)
        {
            Hbv<Epu> bodHbv154= new Hbv<Epu>();
            Hbv<Atp> bodHbv155= new Hbv<Atp>();
            Hbv<Eqs> bodHbv156= new Hbv<Eqs>();
            Hbv<Etp> bodHbv158= new Hbv<Etp>();
            Hbv<Eqs> bodHbv160= new Hbv<Eqs>();
            Hbv<Asc> bodHbv211= new Hbv<Asc>();
            Hbv<Eul> bodHbv2027= new Hbv<Eul>();
            Hbv<Vbv> bodHbv2262= new Hbv<Vbv>();
            Hbv<Eur> bodHbv2268= new Hbv<Eur>();
            Hbv<Eqs> bodHbv2029= new Hbv<Eqs>();
            Hbv<Etp> bodHbv2035= new Hbv<Etp>();
            Hbv<Eqs> bodHbv2037= new Hbv<Eqs>();
            Hbv<Eul> bodHbv2072= new Hbv<Eul>();
            Hbv<Eur> bodHbv2146= new Hbv<Eur>();
            Hbv<Eqs> bodHbv491= new Hbv<Eqs>();
            Hbv<Vbv> bodHbv2154= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2183= new Hbv<Vbv>();
            Hbv<Eqs> bodHbv1278= new Hbv<Eqs>();
            Hbv<Vbv> bodHbv1279= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2323= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2330= new Hbv<Vbv>();
            Hbv<Etp> bodHbv2337= new Hbv<Etp>();
            Hbv<Atp> bodHbv2338= new Hbv<Atp>();
            Hbv<Eqs> bodHbv2339= new Hbv<Eqs>();
            Hbv<Asc> bodHbv2347= new Hbv<Asc>();
            Hbv<Etp> bodHbv2341= new Hbv<Etp>();
            Hbv<Eqs> bodHbv2343= new Hbv<Eqs>();
            Hbv<Epu> bodHbv2358= new Hbv<Epu>();
            Hbv<Atp> bodHbv2359= new Hbv<Atp>();
            Hbv<Eqs> bodHbv2360= new Hbv<Eqs>();
            Hbv<Etp> bodHbv2362= new Hbv<Etp>();
            Hbv<Eqs> bodHbv2364= new Hbv<Eqs>();
            Hbv<Etp> bodHbv2366= new Hbv<Etp>();
            Hbv<Eqs> bodHbv1348= new Hbv<Eqs>();
            Hbv<Vbv> bodHbv1349= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2392= new Hbv<Vbv>();
            Hbv<Etp> bodHbv2394= new Hbv<Etp>();
            Hbv<Eqs> bodHbv204= new Hbv<Eqs>();
            Hbv<Epu> bodHbv2412= new Hbv<Epu>();
            Hbv<Atp> bodHbv2413= new Hbv<Atp>();
            Hbv<Eqs> bodHbv2414= new Hbv<Eqs>();
            Hbv<Etp> bodHbv2416= new Hbv<Etp>();
            Hbv<Eqs> bodHbv453= new Hbv<Eqs>();
            Hbv<Vbv> bodHbv454= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2862= new Hbv<Vbv>();
            Hbv<Etp> bodHbv2864= new Hbv<Etp>();
            Hbv<Eqs> bodHbv301= new Hbv<Eqs>();
            Hbv<Vbv> bodHbv302= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2866= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv2422= new Hbv<Vbv>();
            Hbv<Asc> bodHbv2456= new Hbv<Asc>();
            Hbv<Epu> bodHbv2874= new Hbv<Epu>();
            Hbv<Atp> bodHbv2875= new Hbv<Atp>();
            Hbv<Eqs> bodHbv2876= new Hbv<Eqs>();
            Hbv<Etp> bodHbv2878= new Hbv<Etp>();
            Hbv<Eqs> bodHbv280= new Hbv<Eqs>();
            Hbv<Eul> bodHbv3480= new Hbv<Eul>();
            Hbv<Vbv> bodHbv3760= new Hbv<Vbv>();
            Hbv<Eur> bodHbv3766= new Hbv<Eur>();
            Hbv<Vbv> bodHbv48955= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv49056= new Hbv<Vbv>();
            Hbv<Etp> bodHbv49063= new Hbv<Etp>();
            Hbv<Eqs> bodHbv49065= new Hbv<Eqs>();
            Hbv<Etp> bodHbv49067= new Hbv<Etp>();
            Hbv<Eul> bodHbv49094= new Hbv<Eul>();
            Hbv<Eqs> bodHbv750= new Hbv<Eqs>();
            Hbv<Vbv> bodHbv766= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv49111= new Hbv<Vbv>();
            Hbv<Eur> bodHbv49115= new Hbv<Eur>();
            Hbv<Vbv> bodHbv49117= new Hbv<Vbv>();
            Hbv<Vbv> bodHbv59773= new Hbv<Vbv>();
            Pou pou = pouOutline;

            Tst tifStep0 = new Tst(pouOutline);
            Tst tifStep1 = new Tst(pouOutline);
            Tst tifStep2 = new Tst(pouOutline);
            Tst tifStep3 = new Tst(pouOutline);
            Tst tifStep4 = new Tst(pouOutline);
            Tst tifStep5 = new Tst(pouOutline);
            Tst tifStep6 = new Tst(pouOutline);
            Tst tifStep7 = new Tst(pouOutline);
            Tst tifStep8 = new Tst(pouOutline);
            Tst tifStep9 = new Tst(pouOutline);
            Tst tifStep10 = new Tst(pouOutline);
            Tst tifStep11 = new Tst(pouOutline);
            Tst tifStep12 = new Tst(pouOutline);
            Tst tifStep13 = new Tst(pouOutline);
            Tst tifStep14 = new Tst(pouOutline);
            Tst tifStep15 = new Tst(pouOutline);
            Tst tifStep16 = new Tst(pouOutline);
            Tst tifStep17 = new Tst(pouOutline);
            Tst tifStep18 = new Tst(pouOutline);
            Tst tifStep19 = new Tst(pouOutline);
            Tst tifStep20 = new Tst(pouOutline);
            Tst tifStep21 = new Tst(pouOutline);
            Tst tifStep22 = new Tst(pouOutline);
            Tst tifStep23 = new Tst(pouOutline);
            Tst tifStep24 = new Tst(pouOutline);
            Tst tifStep25 = new Tst(pouOutline);
            Tst tifStep26 = new Tst(pouOutline);
            Tst tifStep27 = new Tst(pouOutline);
            Tst tifStep28 = new Tst(pouOutline);
            Tst tifStep29 = new Tst(pouOutline);
            Tst tifStep30 = new Tst(pouOutline);
            Tst tifStep31 = new Tst(pouOutline);
            Tst tifStep32 = new Tst(pouOutline);
            Tst tifStep33 = new Tst(pouOutline);
            Tst tifStep34 = new Tst(pouOutline);
            Tst tifStep35 = new Tst(pouOutline);
            Tst tifStep36 = new Tst(pouOutline);
            Tst tifStep37 = new Tst(pouOutline);
            Tst tifStep38 = new Tst(pouOutline);
            Tst tifStep39 = new Tst(pouOutline);
            Tst tifStep40 = new Tst(pouOutline);
            Tst tifStep41 = new Tst(pouOutline);
            Tst tifStep42 = new Tst(pouOutline);
            Tst tifStep43 = new Tst(pouOutline);
            Tst tifStep44 = new Tst(pouOutline);
            Tst tifStep45 = new Tst(pouOutline);
            Tst tifStep46 = new Tst(pouOutline);
            Tst tifStep47 = new Tst(pouOutline);
            Tst tifStep48 = new Tst(pouOutline);
            Tst tifStep49 = new Tst(pouOutline);
            Tst tifStep50 = new Tst(pouOutline);
            Tst tifStep51 = new Tst(pouOutline);
            Tst tifStep52 = new Tst(pouOutline);
            Tst tifStep53 = new Tst(pouOutline);
            Tst tifStep54 = new Tst(pouOutline);
            Tst tifStep55 = new Tst(pouOutline);
            Tst tifStep56 = new Tst(pouOutline);
            Tst tifStep57 = new Tst(pouOutline);
            Tst tifStep58 = new Tst(pouOutline);
            Tst tifStep59 = new Tst(pouOutline);
            Tst tifStep60 = new Tst(pouOutline);
            Tst tifStep61 = new Tst(pouOutline);
            Tst tifStep62 = new Tst(pouOutline);
            Tst tifStep63 = new Tst(pouOutline);
            Tst tifStep64 = new Tst(pouOutline);
            Tst tifStep65 = new Tst(pouOutline);
            Tst tifStep66 = new Tst(pouOutline);
            Tst tifStep67 = new Tst(pouOutline);
            Tst tifStep68 = new Tst(pouOutline);
            Tst tifStep69 = new Tst(pouOutline);
            Tst tifStep70 = new Tst(pouOutline);
            Tst tifStep71 = new Tst(pouOutline);
            Tst tifStep72 = new Tst(pouOutline);
            Tst tifStep73 = new Tst(pouOutline);
            Tst tifStep74 = new Tst(pouOutline);
            Tst tifStep75 = new Tst(pouOutline);
            Tst tifStep76 = new Tst(pouOutline);
            Tst tifStep77 = new Tst(pouOutline);
            Tst tifStep78 = new Tst(pouOutline);
            Tst tifStep79 = new Tst(pouOutline);
            Tst tifStep80 = new Tst(pouOutline);
            Tst tifStep81 = new Tst(pouOutline);
            Tst tifStep82 = new Tst(pouOutline);
            Tst tifStep83 = new Tst(pouOutline);
            Tst tifStep84 = new Tst(pouOutline);
            Tst tifStep85 = new Tst(pouOutline);

            Tos tibStmt3 = new Tos(tifStep0);
            tibStmt3.SetLeft (pou.ivbGet<Asc>("ax3"));
            tibStmt3.SetRight (pou.ivbGet<Asc>("ax6"));
            tibStmt3.SetNextTst(tifStep1);
            Tod tibStmt6 = new Tod(tifStep1);
            tibStmt6.kKind = KCapture.kData;
            tibStmt6.hbvPlace = bodHbv154;
            Top tibStmt7 = new Top(tifStep1);
            tibStmt7.SetTarget (bodHbv154);
            tibStmt7.SetInput (null);
            tibStmt7.SetTcd(Tcd.tcdEqsForEpu);
            tibStmt7.SetNextTst(tifStep2);
            tibStmt7.SetLabel("make Epu from two asc");
            Tod tibStmt10 = new Tod(tifStep2);
            tibStmt10.kKind = KCapture.kData;
            tibStmt10.hbvPlace = bodHbv155;
            Toa tibStmt11 = new Toa(tifStep2);
            tibStmt11.SetTff (TAtpToEqs.tff);
            tibStmt11.SetResult (bodHbv156);
            tibStmt11.SetArgs (bodHbv155);
            Tod tibStmt12 = new Tod(tifStep2);
            tibStmt12.kKind = KCapture.kResult;
            tibStmt12.hbvPlace = bodHbv156;


            Tow tibStmt13 = new Tow(tifStep2);
            tibStmt13.SetToWatch (bodHbv156);
            tibStmt13.SetNextTst(tifStep3);
           // 
            Toh<Pti> tibStmt14 = new Toh<Pti>(tifStep0);
            tibStmt14.SetName ("pti2LtR");
            tibStmt14.SetTinName ("Pti");
            tibStmt14.SetValue (pou.vrfGet<Pti>("pti2LtR"));
            Toh<Pti> tibStmt15 = new Toh<Pti>(tifStep0);
            tibStmt15.SetName ("pti4LtR");
            tibStmt15.SetTinName ("Pti");
            tibStmt15.SetValue (pou.vrfGet<Pti>("pti4LtR"));
            Toh<Pti> tibStmt16 = new Toh<Pti>(tifStep0);
            tibStmt16.SetName ("pti5RtL");
            tibStmt16.SetTinName ("Pti");
            tibStmt16.SetValue (pou.vrfGet<Pti>("pti5RtL"));
            //
            Top tibStmt23 = new Top(tifStep3);
            tibStmt23.SetTarget (bodHbv156);
            tibStmt23.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt23.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt23.SetNextTst(tifStep4);
            tibStmt23.SetLabel("find first child eqs for eqsToSolve");
            Tod tibStmt27 = new Tod(tifStep4);
            tibStmt27.kKind = KCapture.kData;
            tibStmt27.hbvPlace = bodHbv158;
            //

            Toa tibStmt28 = new Toa(tifStep4);
            tibStmt28.SetTff (TfEtpToEqs.tff);
            tibStmt28.SetResult (bodHbv160);
            tibStmt28.SetArgs (bodHbv158);
            Tod tibStmt29 = new Tod(tifStep4);
            tibStmt29.kKind = KCapture.kResult;
            tibStmt29.hbvPlace = bodHbv160;
            //
            Top tibStmt30 = new Top(tifStep4);
            tibStmt30.SetTarget (bodHbv160);
            tibStmt30.SetInput (pou.vrfGet<Pti>("pti2LtR"));
            tibStmt30.SetTcd(Tcd.tcdApplyPtiToEqs);
            tibStmt30.SetNextTst(tifStep5);
            tibStmt30.SetLabel("find eul for (F @0 E) => @0");
            Tod tibStmt107 = new Tod(tifStep5);
            tibStmt107.kKind = KCapture.kData;
            tibStmt107.hbvPlace = bodHbv2027;
            Tog tibStmt108 = new Tog(tifStep5);
            tibStmt108.SetTarget (bodHbv2027);
            tibStmt108.SetTcd(Tcd.tcdLaunchEur);
            tibStmt108.SetNextTst(tifStep6);
            Tod tibStmt117 = new Tod(tifStep6);
            tibStmt117.kKind = KCapture.kRight;
            tibStmt117.hbvPlace = bodHbv2262;
            Tod tibStmt118 = new Tod(tifStep6);
            tibStmt118.kKind = KCapture.kData;
            tibStmt118.hbvPlace = bodHbv2268;
            Toa tibStmt119 = new Toa(tifStep6);
            tibStmt119.SetTff (TEqsSub.tff);
            tibStmt119.SetResult (bodHbv2029);
            tibStmt119.SetArgs (bodHbv2027);
            Tod tibStmt120 = new Tod(tifStep6);
            tibStmt120.kKind = KCapture.kResult;
            tibStmt120.hbvPlace = bodHbv2029;   // is this needed?
            Tow tibStmt121 = new Tow(tifStep6);
            tibStmt121.SetToWatch (bodHbv2029);
            tibStmt121.SetNextTst(tifStep7);
            //

            // start a Etp, trivial first child, second child is pti4LtR
            Top tibStmt215 = new Top(tifStep7);
            tibStmt215.SetTarget (bodHbv2029);
            tibStmt215.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt215.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt215.SetNextTst(tifStep8);
            tibStmt215.SetLabel("first etp looking for soln using 4");
            Top tibStmt216 = new Top(tifStep7);
            tibStmt216.SetTarget (bodHbv2029);
            tibStmt216.SetInput (pou.vrfGet<Nin>("nin3"));
            tibStmt216.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt216.SetNextTst(tifStep9);
            tibStmt216.SetLabel("first etp looking for soln using 4, 2nd child");
            Tod tibStmt223 = new Tod(tifStep9);
            tibStmt223.kKind = KCapture.kData;
            tibStmt223.hbvPlace = bodHbv2035;
            Toa tibStmt224 = new Toa(tifStep9);
            tibStmt224.SetTff (TfEtpToEqs.tff);
            tibStmt224.SetResult (bodHbv2037);
            tibStmt224.SetArgs (bodHbv2035);
            Tod tibStmt225 = new Tod(tifStep9);
            tibStmt225.kKind = KCapture.kResult;
            tibStmt225.hbvPlace = bodHbv2037;

            // where to add watch. end of loop for TpEtp?
            Tow tibStmt226 = new Tow(tifStep9);
            tibStmt226.SetToWatch (bodHbv2037);
            tibStmt226.SetNextTst(tifStep10);

            // create TpEul to apply pti, (match TpEul)
            Top tibStmt326 = new Top(tifStep10);
            tibStmt326.SetTarget (bodHbv2037);   // TpEul.hbvEqsInput
            tibStmt326.SetInput (pou.vrfGet<Pti>("pti4LtR"));
            tibStmt326.SetTcd(Tcd.tcdApplyPtiToEqs);
            tibStmt326.SetNextTst(tifStep11);
            tibStmt326.SetLabel("eul for pti 4 to (((F  @0 @1)) (E))");
            Tod tibStmt337 = new Tod(tifStep11);
            tibStmt337.kKind = KCapture.kData;
            tibStmt337.hbvPlace = bodHbv2072;
            Tog tibStmt338 = new Tog(tifStep11);
            tibStmt338.SetTarget (bodHbv2072);
            tibStmt338.SetTcd(Tcd.tcdLaunchEur);
            tibStmt338.SetNextTst(tifStep12);
            Tod tibStmt341 = new Tod(tifStep12);
            tibStmt341.kKind = KCapture.kData;
            tibStmt341.hbvPlace = bodHbv2146;

            // this is different from TpEul: line 245  => TpGetEqsPhase1Pti4Up
            Toi tibStmt342 = new Toi(tifStep12);
            tibStmt342.SetInput (bodHbv2146);
            tibStmt342.SetTcd(Tcd.tcdTransferLeftEqs);  // store request to match left and right 
            tibStmt342.SetNextTst(tifStep13);
            Tod tibStmt343 = new Tod(tifStep13);
            tibStmt343.kKind = KCapture.kLeft;
            tibStmt343.hbvPlace = bodHbv491;
            Toi tibStmt345 = new Toi(tifStep13);
            tibStmt345.SetInput (bodHbv491);
            tibStmt345.SetTcd(Tcd.tcdEqsToEnt);
            tibStmt345.SetNextTst(tifStep14);   // junk?
            Top tibStmt346 = new Top(tifStep13);
            tibStmt346.SetTarget (bodHbv2146);
            tibStmt346.SetInput (bodHbv491);
            tibStmt346.SetTcd(Tcd.tcdEqsToEnt);
            tibStmt346.SetNextTst(tifStep15);
            tibStmt346.SetLabel("solns coming from eqsEE to pti4");
            Top tibStmt353 = new Top(tifStep15);
            tibStmt353.SetTarget (bodHbv2037);
            tibStmt353.SetInput (bodHbv2146);
            tibStmt353.SetTcd(Tcd.tcdEurToNotifyEqs);
            tibStmt353.SetNextTst(tifStep16);
            tibStmt353.SetLabel("soln from eqsEE using pti4 to {{eqs#8103 (((F  @0 @1)) (E))}");
            Tod tibStmt356 = new Tod(tifStep16);
            tibStmt356.kKind = KCapture.kData;
            tibStmt356.hbvPlace = bodHbv2154;
            Top tibStmt357 = new Top(tifStep16);
            tibStmt357.SetTarget (bodHbv2035);
            tibStmt357.SetInput (bodHbv2154);
            tibStmt357.SetTcd(Tcd.tcdSolnToEqs);
            tibStmt357.SetNextTst(tifStep17);
            tibStmt357.SetLabel("process soln from eqsEE using pti4 to {{eqs#8103 (((F  @0 @1)) (E))}");
            Top tibStmt362 = new Top(tifStep17);
            tibStmt362.SetTarget (bodHbv2035);
            tibStmt362.SetInput (bodHbv2154);
            tibStmt362.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt362.SetNextTst(tifStep18);
            tibStmt362.SetLabel("get merged pti4/EE vbv from etp of ax3 and ax1");
            Tod tibStmt365 = new Tod(tifStep18);
            tibStmt365.kKind = KCapture.kData;
            tibStmt365.hbvPlace = bodHbv2183;
            Toa tibStmt366 = new Toa(tifStep18);
            tibStmt366.SetTff (TfFindDup.tff);
            tibStmt366.SetResult (bodHbv2183);
            tibStmt366.SetArgs (bodHbv2029);
            tibStmt366.SetArgs (bodHbv2183);
            Tow tibStmt368 = new Tow(tifStep18);
            tibStmt368.SetToWatch (bodHbv2183);
            tibStmt368.SetNextTst(tifStep19);

            // start back up
            Top tibStmt506 = new Top(tifStep19);
            tibStmt506.SetTarget (bodHbv2027);
            tibStmt506.SetInput (bodHbv2183);
            tibStmt506.SetTcd(Tcd.tcdMapEuhSoln);
            tibStmt506.SetNextTst(tifStep20);
            tibStmt506.SetLabel("map vbv by eulPti2FirstChild");
            Top tibStmt518 = new Top(tifStep20);
            tibStmt518.SetTarget (bodHbv2027);
            tibStmt518.SetInput (bodHbv2262);
            tibStmt518.SetTcd(Tcd.tcdLaunchEur);
            tibStmt518.SetNextTst(tifStep21);
            tibStmt518.SetLabel("eur from eulPti2FirstChild");
            Top tibStmt527 = new Top(tifStep21);
            tibStmt527.SetTarget (bodHbv2268);
            tibStmt527.SetInput (bodHbv2262);
            tibStmt527.SetTcd(Tcd.tcdStartSubproblem);
            tibStmt527.SetNextTst(tifStep22);
            tibStmt527.SetLabel("eqsSub for eurPti2FirstChild");
            Tod tibStmt530 = new Tod(tifStep22);
            tibStmt530.kKind = KCapture.kData;
            tibStmt530.hbvPlace = bodHbv1278;
            Top tibStmt531 = new Top(tifStep22);
            tibStmt531.SetTarget (bodHbv2268);
            tibStmt531.SetInput (bodHbv1278);
            tibStmt531.SetTcd(Tcd.tcdEqsToEnt);
            tibStmt531.SetNextTst(tifStep23);
            tibStmt531.SetLabel("soln for eurPti2FirstChild2");
            Tod tibStmt537 = new Tod(tifStep23);
            tibStmt537.kKind = KCapture.kData;
            tibStmt537.hbvPlace = bodHbv1279;
            Top tibStmt538 = new Top(tifStep23);
            tibStmt538.SetTarget (bodHbv2268);
            tibStmt538.SetInput (bodHbv1279);
            tibStmt538.SetTcd(Tcd.tcdMapEuhSoln);
            tibStmt538.SetNextTst(tifStep24);
            tibStmt538.SetLabel("map soln for eurPti2FirstChild2");
            Tod tibStmt541 = new Tod(tifStep24);
            tibStmt541.kKind = KCapture.kData;
            tibStmt541.hbvPlace = bodHbv2323;
            Top tibStmt542 = new Top(tifStep24);
            tibStmt542.SetTarget (bodHbv160);
            tibStmt542.SetInput (bodHbv2268);
            tibStmt542.SetTcd(Tcd.tcdEurToNotifyEqs);
            tibStmt542.SetNextTst(tifStep25);
            tibStmt542.SetLabel("eurPti2FirstChild2 soln to lhs of 3vs6");
            Top tibStmt546 = new Top(tifStep25);
            tibStmt546.SetTarget (bodHbv158);
            tibStmt546.SetInput (bodHbv2323);
            tibStmt546.SetTcd(Tcd.tcdSolnToEqs);
            tibStmt546.SetNextTst(tifStep26);
            tibStmt546.SetLabel("soln to lhs of 3vs6 of eqsFirstChildEqsToSolve");
            Top tibStmt550 = new Top(tifStep26);
            tibStmt550.SetTarget (bodHbv158);
            tibStmt550.SetInput (bodHbv2323);
            tibStmt550.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt550.SetNextTst(tifStep27);
            tibStmt550.SetLabel("combine soln to rhs of 3vs6 of eqsFirstChildEqsToSolve");
            Tod tibStmt553 = new Tod(tifStep27);
            tibStmt553.kKind = KCapture.kData;
            tibStmt553.hbvPlace = bodHbv2330;
            Top tibStmt554 = new Top(tifStep27);
            tibStmt554.SetTarget (bodHbv158);
            tibStmt554.SetInput (bodHbv2330);
            tibStmt554.SetTcd(Tcd.tcdRegisterEtpByVbv);
            tibStmt554.SetNextTst(tifStep28);
            tibStmt554.SetLabel("report soln to lhs of 3vs6 of eqsFirstChildEqsToSolve");
            Tod tibStmt557 = new Tod(tifStep28);
            tibStmt557.kKind = KCapture.kData;
            tibStmt557.hbvPlace = bodHbv2337;
            Toa tibStmt558 = new Toa(tifStep28);
            tibStmt558.SetTff (TfAtpChild.tff);
            tibStmt558.SetResult (bodHbv2338);
            tibStmt558.SetArgs (bodHbv2337);
            Tod tibStmt559 = new Tod(tifStep28);
            tibStmt559.kKind = KCapture.kResult;
            tibStmt559.hbvPlace = bodHbv2338;
            Tog tibStmt560 = new Tog(tifStep28);
            tibStmt560.SetTarget (bodHbv2338);
            tibStmt560.SetTcd(Tcd.tcdNewEqs);
            tibStmt560.SetNextTst(tifStep29);
            Tod tibStmt562 = new Tod(tifStep29);
            tibStmt562.kKind = KCapture.kRight;
            tibStmt562.hbvPlace = bodHbv2339;
            Tog tibStmt563 = new Tog(tifStep29);
            tibStmt563.SetTarget (bodHbv2339);
            tibStmt563.SetTcd(Tcd.tcdEqsToNgc);
            tibStmt563.SetNextTst(tifStep30);
            Tow tibStmt568 = new Tow(tifStep30);
            tibStmt568.SetToWatch (bodHbv2339);
            tibStmt568.SetNextTst(tifStep31);
            Top tibStmt762 = new Top(tifStep31);
            tibStmt762.SetTarget (bodHbv2339);
            tibStmt762.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt762.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt762.SetNextTst(tifStep32);
            tibStmt762.SetLabel("find etp posn where ngc needed");
            Tod tibStmt769 = new Tod(tifStep32);
            tibStmt769.kKind = KCapture.kData;
            tibStmt769.hbvPlace = bodHbv2341;
            Toa tibStmt770 = new Toa(tifStep32);
            tibStmt770.SetTff (TfEtpToEqs.tff);
            tibStmt770.SetResult (bodHbv2343);
            tibStmt770.SetArgs (bodHbv2341);
            Tod tibStmt771 = new Tod(tifStep32);
            tibStmt771.kKind = KCapture.kResult;
            tibStmt771.hbvPlace = bodHbv2343;
            Tow tibStmt772 = new Tow(tifStep32);
            tibStmt772.SetToWatch (bodHbv2343);
            tibStmt772.SetNextTst(tifStep33);
            Tog tibStmt971 = new Tog(tifStep33);
            tibStmt971.SetTarget (bodHbv2343);
            tibStmt971.SetTcd(Tcd.tcdEqsToNgc);
            tibStmt971.SetNextTst(tifStep34);
            Tod tibStmt974 = new Tod(tifStep34);
            tibStmt974.kKind = KCapture.kData;
            tibStmt974.hbvPlace = bodHbv2347;
            Toh<Asc> tibStmt975 = new Toh<Asc>(tifStep34);
            tibStmt975.SetName ("NgcFC0B");
            tibStmt975.SetTinName ("Asc");
            tibStmt975.SetValue (bodHbv2347);
            Tos tibStmt976 = new Tos(tifStep34);
            tibStmt976.SetLeft (pou.ivbGet<Asc>("ax3"));
            tibStmt976.SetRight (pou.ivbGet<Asc>("NgcFC0B"));
            tibStmt976.SetNextTst(tifStep35);
            Tod tibStmt989 = new Tod(tifStep35);
            tibStmt989.kKind = KCapture.kData;
            tibStmt989.hbvPlace = bodHbv2358;
            Top tibStmt990 = new Top(tifStep35);
            tibStmt990.SetTarget (bodHbv2358);
            tibStmt990.SetInput (null);
            tibStmt990.SetTcd(Tcd.tcdEqsForEpu);
            tibStmt990.SetNextTst(tifStep36);
            tibStmt990.SetLabel("make Epu from two asc");
            Tod tibStmt994 = new Tod(tifStep36);
            tibStmt994.kKind = KCapture.kData;
            tibStmt994.hbvPlace = bodHbv2359;
            Toa tibStmt995 = new Toa(tifStep36);
            tibStmt995.SetTff (TAtpToEqs.tff);
            tibStmt995.SetResult (bodHbv2360);
            tibStmt995.SetArgs (bodHbv2359);
            Tod tibStmt996 = new Tod(tifStep36);
            tibStmt996.kKind = KCapture.kResult;
            tibStmt996.hbvPlace = bodHbv2360;
            Tow tibStmt997 = new Tow(tifStep36);
            tibStmt997.SetToWatch (bodHbv2360);
            tibStmt997.SetNextTst(tifStep37);
            Top tibStmt1216 = new Top(tifStep37);
            tibStmt1216.SetTarget (bodHbv2360);
            tibStmt1216.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt1216.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt1216.SetNextTst(tifStep38);
            tibStmt1216.SetLabel("find first child eqs for eqsToSolve");
            Tod tibStmt1220 = new Tod(tifStep38);
            tibStmt1220.kKind = KCapture.kData;
            tibStmt1220.hbvPlace = bodHbv2362;
            Toa tibStmt1221 = new Toa(tifStep38);
            tibStmt1221.SetTff (TfEtpToEqs.tff);
            tibStmt1221.SetResult (bodHbv2364);
            tibStmt1221.SetArgs (bodHbv2362);
            Tod tibStmt1222 = new Tod(tifStep38);
            tibStmt1222.kKind = KCapture.kResult;
            tibStmt1222.hbvPlace = bodHbv2364;
            Tow tibStmt1223 = new Tow(tifStep38);
            tibStmt1223.SetToWatch (bodHbv2364);
            tibStmt1223.SetNextTst(tifStep39);
            Top tibStmt1444 = new Top(tifStep39);
            tibStmt1444.SetTarget (bodHbv2364);
            tibStmt1444.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt1444.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt1444.SetNextTst(tifStep40);
            tibStmt1444.SetLabel("find first child lsh eqs of eqsToSolve");
            Tod tibStmt1447 = new Tod(tifStep40);
            tibStmt1447.kKind = KCapture.kData;
            tibStmt1447.hbvPlace = bodHbv2366;
            Toa tibStmt1448 = new Toa(tifStep40);
            tibStmt1448.SetTff (TfEtpToEqs.tff);
            tibStmt1448.SetResult (bodHbv1348);
            tibStmt1448.SetArgs (bodHbv2366);
            Tod tibStmt1449 = new Tod(tifStep40);
            tibStmt1449.kKind = KCapture.kResult;
            tibStmt1449.hbvPlace = bodHbv1348;
            Tow tibStmt1450 = new Tow(tifStep40);
            tibStmt1450.SetToWatch (bodHbv1348);
            tibStmt1450.SetNextTst(tifStep41);
            Tow tibStmt1678 = new Tow(tifStep40);
            tibStmt1678.SetToWatch (bodHbv2366);
            tibStmt1678.SetNextTst(tifStep42);
            Top tibStmt1902 = new Top(tifStep42);
            tibStmt1902.SetTarget (bodHbv2366);
            tibStmt1902.SetInput (bodHbv1348);
            tibStmt1902.SetTcd(Tcd.tcdEqsToEnt);
            tibStmt1902.SetNextTst(tifStep43);
            tibStmt1902.SetLabel("apply soln from eqs0C to second arg");
            Tod tibStmt1921 = new Tod(tifStep43);
            tibStmt1921.kKind = KCapture.kData;
            tibStmt1921.hbvPlace = bodHbv1349;
            Top tibStmt1922 = new Top(tifStep43);
            tibStmt1922.SetTarget (bodHbv2366);
            tibStmt1922.SetInput (bodHbv1349);
            tibStmt1922.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt1922.SetNextTst(tifStep44);
            tibStmt1922.SetLabel("apply soln to etpSecondArg");
            Tod tibStmt1925 = new Tod(tifStep44);
            tibStmt1925.kKind = KCapture.kData;
            tibStmt1925.hbvPlace = bodHbv2392;
            Top tibStmt1926 = new Top(tifStep44);
            tibStmt1926.SetTarget (bodHbv2366);
            tibStmt1926.SetInput (bodHbv2392);
            tibStmt1926.SetTcd(Tcd.tcdRegisterEtpByVbv);
            tibStmt1926.SetNextTst(tifStep45);
            tibStmt1926.SetLabel("apply soln from eqs0C to second arg");
            Tod tibStmt1929 = new Tod(tifStep45);
            tibStmt1929.kKind = KCapture.kData;
            tibStmt1929.hbvPlace = bodHbv2394;
            Toa tibStmt1930 = new Toa(tifStep45);
            tibStmt1930.SetTff (TfEtpToEqs.tff);
            tibStmt1930.SetResult (bodHbv204);
            tibStmt1930.SetArgs (bodHbv2394);
            Tod tibStmt1931 = new Tod(tifStep45);
            tibStmt1931.kKind = KCapture.kResult;
            tibStmt1931.hbvPlace = bodHbv204;
            Tow tibStmt1932 = new Tow(tifStep45);
            tibStmt1932.SetToWatch (bodHbv204);
            tibStmt1932.SetNextTst(tifStep46);
            Tog tibStmt1953 = new Tog(tifStep46);
            tibStmt1953.SetTarget (bodHbv204);
            tibStmt1953.SetTcd(Tcd.tcdEqsToNgc);
            tibStmt1953.SetNextTst(tifStep47);
            Tod tibStmt1956 = new Tod(tifStep47);
            tibStmt1956.kKind = KCapture.kData;
            tibStmt1956.hbvPlace = bodHbv211;
            Toh<Asc> tibStmt1957 = new Toh<Asc>(tifStep47);
            tibStmt1957.SetName ("NgcF012");
            tibStmt1957.SetTinName ("Asc");
            tibStmt1957.SetValue (bodHbv211);
            Tos tibStmt1958 = new Tos(tifStep47);
            tibStmt1958.SetLeft (pou.ivbGet<Asc>("axR"));
            tibStmt1958.SetRight (pou.ivbGet<Asc>("NgcF012"));
            tibStmt1958.SetNextTst(tifStep48);
            Tod tibStmt2195 = new Tod(tifStep48);
            tibStmt2195.kKind = KCapture.kData;
            tibStmt2195.hbvPlace = bodHbv2412;
            Top tibStmt2196 = new Top(tifStep48);
            tibStmt2196.SetTarget (bodHbv2412);
            tibStmt2196.SetInput (null);
            tibStmt2196.SetTcd(Tcd.tcdEqsForEpu);
            tibStmt2196.SetNextTst(tifStep49);
            tibStmt2196.SetLabel("make Epu from two asc");
            Tod tibStmt2198 = new Tod(tifStep49);
            tibStmt2198.kKind = KCapture.kData;
            tibStmt2198.hbvPlace = bodHbv2413;
            Toa tibStmt2199 = new Toa(tifStep49);
            tibStmt2199.SetTff (TAtpToEqs.tff);
            tibStmt2199.SetResult (bodHbv2414);
            tibStmt2199.SetArgs (bodHbv2413);
            Tod tibStmt2200 = new Tod(tifStep49);
            tibStmt2200.kKind = KCapture.kResult;
            tibStmt2200.hbvPlace = bodHbv2414;
            Tow tibStmt2201 = new Tow(tifStep49);
            tibStmt2201.SetToWatch (bodHbv2414);
            tibStmt2201.SetNextTst(tifStep50);
            Top tibStmt2466 = new Top(tifStep50);
            tibStmt2466.SetTarget (bodHbv2414);
            tibStmt2466.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt2466.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt2466.SetNextTst(tifStep51);
            tibStmt2466.SetLabel("find first child eqs for eqsToSolve");
            Tod tibStmt2469 = new Tod(tifStep51);
            tibStmt2469.kKind = KCapture.kData;
            tibStmt2469.hbvPlace = bodHbv2416;
            Toa tibStmt2470 = new Toa(tifStep51);
            tibStmt2470.SetTff (TfEtpToEqs.tff);
            tibStmt2470.SetResult (bodHbv453);
            tibStmt2470.SetArgs (bodHbv2416);
            Tod tibStmt2471 = new Tod(tifStep51);
            tibStmt2471.kKind = KCapture.kResult;
            tibStmt2471.hbvPlace = bodHbv453;
            Top tibStmt2472 = new Top(tifStep51);
            tibStmt2472.SetTarget (bodHbv2416);
            tibStmt2472.SetInput (bodHbv453);
            tibStmt2472.SetTcd(Tcd.tcdEqsToEnt);
            tibStmt2472.SetNextTst(tifStep52);
            tibStmt2472.SetLabel("match first arg");
            Tod tibStmt2490 = new Tod(tifStep52);
            tibStmt2490.kKind = KCapture.kData;
            tibStmt2490.hbvPlace = bodHbv454;
            Top tibStmt2491 = new Top(tifStep52);
            tibStmt2491.SetTarget (bodHbv2416);
            tibStmt2491.SetInput (bodHbv454);
            tibStmt2491.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt2491.SetNextTst(tifStep53);
            tibStmt2491.SetLabel("merge soln from skip 4 and 2");
            Tod tibStmt2494 = new Tod(tifStep53);
            tibStmt2494.kKind = KCapture.kData;
            tibStmt2494.hbvPlace = bodHbv2862;
            Top tibStmt2495 = new Top(tifStep53);
            tibStmt2495.SetTarget (bodHbv2416);
            tibStmt2495.SetInput (bodHbv2862);
            tibStmt2495.SetTcd(Tcd.tcdRegisterEtpByVbv);
            tibStmt2495.SetNextTst(tifStep54);
            tibStmt2495.SetLabel("second arg after 0~(F23)");
            Tod tibStmt2498 = new Tod(tifStep54);
            tibStmt2498.kKind = KCapture.kData;
            tibStmt2498.hbvPlace = bodHbv2864;
            Toa tibStmt2499 = new Toa(tifStep54);
            tibStmt2499.SetTff (TfEtpToEqs.tff);
            tibStmt2499.SetResult (bodHbv301);
            tibStmt2499.SetArgs (bodHbv2864);
            Tod tibStmt2500 = new Tod(tifStep54);
            tibStmt2500.kKind = KCapture.kResult;
            tibStmt2500.hbvPlace = bodHbv301;
            Toa tibStmt2501 = new Toa(tifStep54);
            tibStmt2501.SetTff (TfVbvMinimalSoln.tff);
            tibStmt2501.SetResult (bodHbv302);
            tibStmt2501.SetArgs (bodHbv301);
            Tod tibStmt2502 = new Tod(tifStep54);
            tibStmt2502.kKind = KCapture.kResult;
            tibStmt2502.hbvPlace = bodHbv302;
            Top tibStmt2503 = new Top(tifStep54);
            tibStmt2503.SetTarget (bodHbv2864);
            tibStmt2503.SetInput (bodHbv302);
            tibStmt2503.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt2503.SetNextTst(tifStep55);
            tibStmt2503.SetLabel("immediate vbv after 0~(F23)");
            Tod tibStmt2506 = new Tod(tifStep55);
            tibStmt2506.kKind = KCapture.kData;
            tibStmt2506.hbvPlace = bodHbv2866;
            Toa tibStmt2507 = new Toa(tifStep55);
            tibStmt2507.SetTff (TfEpuToEqs.tff);
            tibStmt2507.SetResult (bodHbv2414);
            tibStmt2507.SetArgs (bodHbv2412);
            Toa tibStmt2509 = new Toa(tifStep55);
            tibStmt2509.SetTff (TfFindDup.tff);
            tibStmt2509.SetResult (bodHbv2422);
            tibStmt2509.SetArgs (bodHbv2414);
            tibStmt2509.SetArgs (bodHbv2866);
            Tod tibStmt2510 = new Tod(tifStep55);
            tibStmt2510.kKind = KCapture.kResult;
            tibStmt2510.hbvPlace = bodHbv2422;
            Tow tibStmt2511 = new Tow(tifStep55);
            tibStmt2511.SetToWatch (bodHbv2422);
            tibStmt2511.SetNextTst(tifStep56);
            Top tibStmt2784 = new Top(tifStep56);
            tibStmt2784.SetTarget (bodHbv2412);
            tibStmt2784.SetInput (bodHbv2422);
            tibStmt2784.SetTcd(Tcd.tcdSolnToEqs);
            tibStmt2784.SetNextTst(tifStep57);
            tibStmt2784.SetLabel("merged vbv to epuR2");
            Top tibStmt2794 = new Top(tifStep57);
            tibStmt2794.SetTarget (pou.vrfGet<Asc>("axR"));
            tibStmt2794.SetInput (bodHbv211);
            tibStmt2794.SetTcd(Tcd.tcdNewAscResolve);
            tibStmt2794.SetNextTst(tifStep58);
            tibStmt2794.SetLabel("ascR from epuR2");
            Tod tibStmt2797 = new Tod(tifStep58);
            tibStmt2797.kKind = KCapture.kData;
            tibStmt2797.hbvPlace = bodHbv2456;
            Toh<Asc> tibStmt2798 = new Toh<Asc>(tifStep58);
            tibStmt2798.SetName ("0_F12");
            tibStmt2798.SetTinName ("Asc");
            tibStmt2798.SetValue (bodHbv2456);
            Tos tibStmt2799 = new Tos(tifStep58);
            tibStmt2799.SetLeft (pou.ivbGet<Asc>("ax3"));
            tibStmt2799.SetRight (pou.ivbGet<Asc>("0_F12"));
            tibStmt2799.SetNextTst(tifStep59);
            Tod tibStmt2834 = new Tod(tifStep59);
            tibStmt2834.kKind = KCapture.kData;
            tibStmt2834.hbvPlace = bodHbv2874;
            Top tibStmt2835 = new Top(tifStep59);
            tibStmt2835.SetTarget (bodHbv2874);
            tibStmt2835.SetInput (null);
            tibStmt2835.SetTcd(Tcd.tcdEqsForEpu);
            tibStmt2835.SetNextTst(tifStep60);
            tibStmt2835.SetLabel("make Epu from two asc");
            Tod tibStmt2838 = new Tod(tifStep60);
            tibStmt2838.kKind = KCapture.kData;
            tibStmt2838.hbvPlace = bodHbv2875;
            Toa tibStmt2839 = new Toa(tifStep60);
            tibStmt2839.SetTff (TAtpToEqs.tff);
            tibStmt2839.SetResult (bodHbv2876);
            tibStmt2839.SetArgs (bodHbv2875);
            Tod tibStmt2840 = new Tod(tifStep60);
            tibStmt2840.kKind = KCapture.kResult;
            tibStmt2840.hbvPlace = bodHbv2876;
            Tow tibStmt2841 = new Tow(tifStep60);
            tibStmt2841.SetToWatch (bodHbv2876);
            tibStmt2841.SetNextTst(tifStep61);
            Top tibStmt3166 = new Top(tifStep61);
            tibStmt3166.SetTarget (bodHbv2876);
            tibStmt3166.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt3166.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt3166.SetNextTst(tifStep62);
            tibStmt3166.SetLabel("find first child eqs for eqsToSolve");
            Tod tibStmt3169 = new Tod(tifStep62);
            tibStmt3169.kKind = KCapture.kData;
            tibStmt3169.hbvPlace = bodHbv2878;
            Toa tibStmt3170 = new Toa(tifStep62);
            tibStmt3170.SetTff (TfEtpToEqs.tff);
            tibStmt3170.SetResult (bodHbv280);
            tibStmt3170.SetArgs (bodHbv2878);
            Tod tibStmt3171 = new Tod(tifStep62);
            tibStmt3171.kKind = KCapture.kResult;
            tibStmt3171.hbvPlace = bodHbv280;
            Tow tibStmt3172 = new Tow(tifStep62);
            tibStmt3172.SetToWatch (bodHbv280);
            tibStmt3172.SetNextTst(tifStep63);
            Top tibStmt3204 = new Top(tifStep63);
            tibStmt3204.SetTarget (bodHbv280);
            tibStmt3204.SetInput (pou.vrfGet<Pti>("pti2LtR"));
            tibStmt3204.SetTcd(Tcd.tcdApplyPtiToEqs);
            tibStmt3204.SetNextTst(tifStep64);
            tibStmt3204.SetLabel("find eul for (F @0 E) => @0");
            Tod tibStmt3525 = new Tod(tifStep64);
            tibStmt3525.kKind = KCapture.kData;
            tibStmt3525.hbvPlace = bodHbv3480;
            Tog tibStmt3526 = new Tog(tifStep64);
            tibStmt3526.SetTarget (bodHbv3480);
            tibStmt3526.SetTcd(Tcd.tcdLaunchEur);
            tibStmt3526.SetNextTst(tifStep65);
            Tod tibStmt3535 = new Tod(tifStep65);
            tibStmt3535.kKind = KCapture.kRight;
            tibStmt3535.hbvPlace = bodHbv3760;
            Tod tibStmt3536 = new Tod(tifStep65);
            tibStmt3536.kKind = KCapture.kData;
            tibStmt3536.hbvPlace = bodHbv3766;
            Top tibStmt3537 = new Top(tifStep65);
            tibStmt3537.SetTarget (bodHbv3766);
            tibStmt3537.SetInput (bodHbv3760);
            tibStmt3537.SetTcd(Tcd.tcdStartSubproblem);
            tibStmt3537.SetNextTst(tifStep66);
            tibStmt3537.SetLabel("phase3 map vbv by eulPti2FirstChild");
            Tow tibStmt3541 = new Tow(tifStep66);
            tibStmt3541.SetToWatch (bodHbv3766);
            tibStmt3541.SetNextTst(tifStep67);
            Top tibStmt3904 = new Top(tifStep67);
            tibStmt3904.SetTarget (bodHbv3766);
            tibStmt3904.SetInput (bodHbv301);
            tibStmt3904.SetTcd(Tcd.tcdEqsToEnt);
            tibStmt3904.SetNextTst(tifStep68);
            tibStmt3904.SetLabel("get eurPti2FirstChild3");
            Top tibStmt4571 = new Top(tifStep68);
            tibStmt4571.SetTarget (bodHbv3766);
            tibStmt4571.SetInput (bodHbv302);
            tibStmt4571.SetTcd(Tcd.tcdMapEuhSoln);
            tibStmt4571.SetNextTst(tifStep69);
            tibStmt4571.SetLabel("get merged vbv with P3 soln to 01");
            Tod tibStmt4574 = new Tod(tifStep69);
            tibStmt4574.kKind = KCapture.kData;
            tibStmt4574.hbvPlace = bodHbv48955;
            Top tibStmt4575 = new Top(tifStep69);
            tibStmt4575.SetTarget (bodHbv280);
            tibStmt4575.SetInput (bodHbv3766);
            tibStmt4575.SetTcd(Tcd.tcdEurToNotifyEqs);
            tibStmt4575.SetNextTst(tifStep70);
            tibStmt4575.SetLabel("send notify to eqsFirstChildEqsToSolve3");
            Top tibStmt4579 = new Top(tifStep70);
            tibStmt4579.SetTarget (bodHbv2878);
            tibStmt4579.SetInput (bodHbv48955);
            tibStmt4579.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt4579.SetNextTst(tifStep71);
            tibStmt4579.SetLabel("get merged vbv for etp using F0F12_3");
            Tod tibStmt4583 = new Tod(tifStep71);
            tibStmt4583.kKind = KCapture.kData;
            tibStmt4583.hbvPlace = bodHbv49056;
            Top tibStmt4584 = new Top(tifStep71);
            tibStmt4584.SetTarget (bodHbv2878);
            tibStmt4584.SetInput (bodHbv49056);
            tibStmt4584.SetTcd(Tcd.tcdRegisterEtpByVbv);
            tibStmt4584.SetNextTst(tifStep72);
            tibStmt4584.SetLabel("second etp for F0F12_3");
            Tod tibStmt4587 = new Tod(tifStep72);
            tibStmt4587.kKind = KCapture.kData;
            tibStmt4587.hbvPlace = bodHbv49063;
            Toa tibStmt4589 = new Toa(tifStep72);
            tibStmt4589.SetTff (TfEtpToEqs.tff);
            tibStmt4589.SetResult (bodHbv49065);
            tibStmt4589.SetArgs (bodHbv49063);
            Tod tibStmt4590 = new Tod(tifStep72);
            tibStmt4590.kKind = KCapture.kResult;
            tibStmt4590.hbvPlace = bodHbv49065;
            Tow tibStmt4591 = new Tow(tifStep72);
            tibStmt4591.SetToWatch (bodHbv49065);
            tibStmt4591.SetNextTst(tifStep73);
            Top tibStmt5639 = new Top(tifStep73);
            tibStmt5639.SetTarget (bodHbv49065);
            tibStmt5639.SetInput (pou.vrfGet<Nin>("nin2"));
            tibStmt5639.SetTcd(Tcd.tcdRegisterEtpByOffset);
            tibStmt5639.SetNextTst(tifStep74);
            tibStmt5639.SetLabel("find first child eqs for eqsFor3rdRhs");
            Tod tibStmt5642 = new Tod(tifStep74);
            tibStmt5642.kKind = KCapture.kData;
            tibStmt5642.hbvPlace = bodHbv49067;
            Toa tibStmt5643 = new Toa(tifStep74);
            tibStmt5643.SetTff (TfEtpToEqs.tff);
            tibStmt5643.SetResult (bodHbv204);
            tibStmt5643.SetArgs (bodHbv49067);
            Tow tibStmt5645 = new Tow(tifStep74);
            tibStmt5645.SetToWatch (bodHbv204);
            tibStmt5645.SetNextTst(tifStep75);
            Tov tibStmt5668 = new Tov(tifStep75);
            tibStmt5668.SetKValue(KTis.kEqsAllowEprNonVbl);
            tibStmt5668.SetValue (bodHbv204);
            Top tibStmt5669 = new Top(tifStep75);
            tibStmt5669.SetTarget (bodHbv204);
            tibStmt5669.SetInput (pou.vrfGet<Pti>("pti5RtL"));
            tibStmt5669.SetTcd(Tcd.tcdApplyPtiToEqs);
            tibStmt5669.SetNextTst(tifStep76);
            tibStmt5669.SetLabel("look for on pti of Ax5 applied to 3rd phase");
            Tod tibStmt6707 = new Tod(tifStep76);
            tibStmt6707.kKind = KCapture.kData;
            tibStmt6707.hbvPlace = bodHbv49094;
            Tog tibStmt6708 = new Tog(tifStep76);
            tibStmt6708.SetTarget (bodHbv49094);
            tibStmt6708.SetTcd(Tcd.tcdStartSubproblem);
            tibStmt6708.SetNextTst(tifStep77);
            Tod tibStmt6710 = new Tod(tifStep77);
            tibStmt6710.kKind = KCapture.kData;
            tibStmt6710.hbvPlace = bodHbv750;
            Tow tibStmt6711 = new Tow(tifStep77);
            tibStmt6711.SetToWatch (bodHbv750);
            tibStmt6711.SetNextTst(tifStep78);
            Top tibStmt7782 = new Top(tifStep77);
            tibStmt7782.SetTarget (bodHbv49094);
            tibStmt7782.SetInput (bodHbv766);
            tibStmt7782.SetTcd(Tcd.tcdMapEuhSoln);
            tibStmt7782.SetNextTst(tifStep80);
            tibStmt7782.SetLabel("soln of F01_FAB to eulEqs3rdAx5");
            Tog tibStmt6767 = new Tog(tifStep78);
            tibStmt6767.SetTarget (bodHbv750);
            tibStmt6767.SetTcd(Tcd.tcdImmediateVbv);
            tibStmt6767.SetNextTst(tifStep79);
            Tod tibStmt6771 = new Tod(tifStep79);
            tibStmt6771.kKind = KCapture.kData;
            tibStmt6771.hbvPlace = bodHbv766;
            Tod tibStmt7785 = new Tod(tifStep80);
            tibStmt7785.kKind = KCapture.kData;
            tibStmt7785.hbvPlace = bodHbv49111;
            Top tibStmt7786 = new Top(tifStep80);
            tibStmt7786.SetTarget (bodHbv49094);
            tibStmt7786.SetInput (bodHbv49111);
            tibStmt7786.SetTcd(Tcd.tcdLaunchEur);
            tibStmt7786.SetNextTst(tifStep81);
            tibStmt7786.SetLabel("eur after F01_FAB to eulEqs3rdAx5");
            Tod tibStmt7789 = new Tod(tifStep81);
            tibStmt7789.kKind = KCapture.kData;
            tibStmt7789.hbvPlace = bodHbv49115;
            Tog tibStmt7790 = new Tog(tifStep81);
            tibStmt7790.SetTarget (bodHbv49115);
            tibStmt7790.SetTcd(Tcd.tcdMapEuhSoln);
            tibStmt7790.SetNextTst(tifStep82);
            Tod tibStmt7793 = new Tod(tifStep82);
            tibStmt7793.kKind = KCapture.kData;
            tibStmt7793.hbvPlace = bodHbv49117;
            Top tibStmt7794 = new Top(tifStep82);
            tibStmt7794.SetTarget (bodHbv49067);
            tibStmt7794.SetInput (bodHbv49117);
            tibStmt7794.SetTcd(Tcd.tcdVbvForEtp);
            tibStmt7794.SetNextTst(tifStep83);
            tibStmt7794.SetLabel("merge soln from F01_FAB to etpFirstChild3rdRhs");
            Tod tibStmt7950 = new Tod(tifStep83);
            tibStmt7950.kKind = KCapture.kData;
            tibStmt7950.hbvPlace = bodHbv59773;
            Top tibStmt7951 = new Top(tifStep83);
            tibStmt7951.SetTarget (bodHbv49067);
            tibStmt7951.SetInput (bodHbv59773);
            tibStmt7951.SetTcd(Tcd.tcdRegisterEtpByVbv);
            tibStmt7951.SetNextTst(tifStep84);
            tibStmt7951.SetLabel("next in etp after F01_FAB to etpFirstChild3rdRhs");
            Tos tibStmt7955 = new Tos(tifStep84);
            tibStmt7955.SetLeft (pou.ivbGet<Asc>("ax3"));
            tibStmt7955.SetRight (pou.ivbGet<Asc>("NgcFC0B"));
            tibStmt7955.SetNextTst(tifStep85);
            Toa tibStmt7959 = new Toa(tifStep85);
            tibStmt7959.SetTff (TffSave.tff);
            tibStmt7959.SetResult (null);
            return pou;
        }
    }
}

